### ISSUE TITLE
Conformance Checker exception on dump of cache

### ISSUE THREAD

**Issue by PhillipWatts1012** [DMTF/Redfish-Service-Conformance-Check#133]
In newest Conformance Check got a crash, below
in rf_sut.py line 159
           print ('TYPE',type(cache_payload))
            print ('PAYLOAD',cache_payload)
            json.dump(cache_payload, fp, sort_keys=True, indent=4)
Type of cache_payload is dict.
Have not been able to debug this.
It looks like the **initialize_cache** ( spelled initalize)  function may be new.

Traceback (most recent call last):
  File "rf_client.py", line 702, in <module>
    main()
  File "rf_client.py", line 694, in main
    rfs_test.run(sut)
  File "/home/dmtf/Redfish-Service-Conformance-Check/rfs_test/__init__.py", line 41, in run
    TEST_protocol_details.run(sut, log)
  File "/home/dmtf/Redfish-Service-Conformance-Check/rfs_test/TEST_protocol_details.py", line 5128, in run
    cacheURI(self)
  File "/home/dmtf/Redfish-Service-Conformance-Check/rfs_test/TEST_protocol_details.py", line 78, in cacheURI
    cached_uri, cached_uri_no_member = self.initalize_cache()
  File "/home/dmtf/Redfish-Service-Conformance-Check/rf_sut.py", line 161, in initalize_cache
    json.dump(cache_payload, fp, sort_keys=True, indent=4)
  File "/usr/lib64/python3.4/json/__init__.py", line 178, in dump
    for chunk in iterable:
  File "/usr/lib64/python3.4/json/encoder.py", line 422, in _iterencode
    yield from _iterencode_dict(o, _current_indent_level)
  File "/usr/lib64/python3.4/json/encoder.py", line 396, in _iterencode_dict
    yield from chunks
  File "/usr/lib64/python3.4/json/encoder.py", line 429, in _iterencode
    o = _default(o)
  File "/usr/lib64/python3.4/json/encoder.py", line 173, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: b'' is not JSON serializable

**Comment by billdodd** [comment]
@PhillipWatts1012  - thanks for the report. It looks like you added a debug statement to print the cache_payload just before the json.dump() call. Can you capture that output and attach it here?

I suspect the function needs some hardening (like checking the status returned from the GET and the types of the json_payload, headers and status before adding them to the cache_payload).

**Comment by PhillipWatts1012** [comment]
Its at the end of this log
[log4.txt](https://github.com/DMTF/Redfish-Service-Conformance-Check/files/2307357/log4.txt)

**Comment by PhillipWatts1012** [comment]
BTW that was with
"Number of URI's to Cache": 50
I ran it earlier with 100.
Same thing happened, just more output.

**Comment by billdodd** [comment]
Thanks for the log. Some of the GETs returned a 404 status and a json_payload that is an empty byte array. The empty byte array (`b''`) cannot be serialized into JSON.

Some updates to the function to validate the results of the GETs should take care of the issue.

**Comment by billdodd** [comment]
@PhillipWatts1012 - FYI, in my PR I've changed the property name from "Number of URI's to Cache" to "NumUrisToCache".
