### ISSUE TITLE
 Assertion: COMP139  Traceback 

### ISSUE THREAD

**Issue by scottbusi** [DMTF/Redfish-Service-Conformance-Check#194]
---> Assertion: COMP139

Traceback (most recent call last):
  File "/Redfish_Conformance_check/Redfish-Service-Conformance-Check-master/rfs_test/TEST_computersystem_schema.py", line 59, in Assertion_COMP139
    json_payload, headers, status = self.http_GET(relative_uris['Root Service_Systems'], rq_headers, authorization)
KeyError: 'Root Service_Systems'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "sample_run.py", line 43, in <module>
    rfs_test.run(sut)
  File "/Redfish_Conformance_check/Redfish-Service-Conformance-Check-master/rfs_test/__init__.py", line 58, in run
    TEST_computersystem_schema.run(sut, log)
  File "/Redfish_Conformance_check/Redfish-Service-Conformance-Check-master/rfs_test/TEST_computersystem_schema.py", line 117, in run
    assertion_status = Assertion_COMP139(self, log)
  File "/Redfish_Conformance_check/Redfish-Service-Conformance-Check-master/rfs_test/TEST_computersystem_schema.py", line 64, in Assertion_COMP139
    log.assertion_log('line', "Resource %s, is not found." % (relative_uris['Root Service_Systems']))
KeyError: 'Root Service_Systems'

**Comment by billdodd** [comment]
The 'Root Service_Systems' KeyError could be from some problem reading resources on your service, or it could be that your service does not have a `Systems` NavigationProperty in the Service Root.

In any case, we have a newer, faster, and more comprehensive protocol validation tool here: [Redfish-Protocol-Validator](https://github.com/DMTF/Redfish-Protocol-Validator)
This tool (Redfish-Service-Conformance-Check) is being deprecated.

Please try out the new tool.

(BTW: I just opened PR #195 to update the README here to note the deprecation and point to the new tool.)

**Comment by mraineri** [comment]
Closing; work is being done in https://github.com/DMTF/Redfish-Protocol-Validator for performing validation to the protocol aspects of the spec.
