### ISSUE TITLE
Fails with latest version of openpyxl

### ISSUE THREAD

**Issue by blakehilliard** [DMTF/Redfish-Service-Conformance-Check#196]
```
Redfish Service Check Tool setup for SUT <host> successfully completed
Running assertions on SUT <host>...
Traceback (most recent call last):
  File ".../Redfish-Service-Conformance-Check/rf_client.py", line 702, in <module>
    main()
  File ".../Redfish-Service-Conformance-Check/rf_client.py", line 694, in main
    rfs_test.run(sut)
  File ".../Redfish-Service-Conformance-Check/rfs_test/__init__.py", line 36, in run
    log.init_xl()
  File ".../Redfish-Service-Conformance-Check/logger.py", line 86, in init_xl
    self.xl_PASS = PatternFill(fill_type='solid', start_color=colors.GREEN, end_color=colors.GREEN)
AttributeError: module 'openpyxl.styles.colors' has no attribute 'GREEN'
```

It works if I put `openpyxl<=3.0.2` in requirements.txt and install that.

**Comment by blakehilliard** [comment]
Nope, didn't notice the deprecation, just had an old tool grabbing this repo running it. I'll switch to Redfish-Protocol-Validator. Thanks!

**Comment by mraineri** [comment]
Closing; tool is not being maintained (replaced by the Redfish Protocol Validator)
