### ISSUE TITLE
Crash on Assertion: 6.5.20

### ISSUE THREAD

**Issue by samerhaj** [DMTF/Redfish-Service-Conformance-Check#21]
The tool run up till 6.5.20 then crashed. It looks like it found an entry in the $metadata for an OEM Schema (OemAuthorization_v1.xml) and decided to go look for it on dmtf.org: http://redfish.dmtf.org/schemas/v1/OemAuthorization_v1.xml, and crashed with HTTP Error 404

---> Assertion: 6.5.20
.....
....
....
The uri is /redfish/v1/metadata/OemAuthorization_v1.xml
OemAuthorization_v1.xml
http://redfish.dmtf.org/schemas/v1/OemAuthorization_v1.xml
Traceback (most recent call last):
  File "rf_client.py", line 779, in <module>
    main()
  File "rf_client.py", line 773, in main
    rfs_test.run(sut)
  File "C:\DevTools\Redfish-Service-Conformance-Check\rfs_test\__init__.py", line 34, in run
    TEST_protocol_details.run(sut, log)
  File "C:\DevTools\Redfish-Service-Conformance-Check\rfs_test\TEST_protocol_details.py", line 5019, in
 run
    assertion_status = Assertion_6_5_20(self, log)
  File "C:\DevTools\Redfish-Service-Conformance-Check\rfs_test\TEST_protocol_details.py", line 3751, in
 Assertion_6_5_20
    f = urllib.request.urlopen(uris)
  File "C:\Users\smahmoud\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\smahmoud\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "C:\Users\smahmoud\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Users\smahmoud\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "C:\Users\smahmoud\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "C:\Users\smahmoud\AppData\Local\Programs\Python\Python35\lib\urllib\request.py", line 590, in http_error_default

    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by billdodd** [comment]
This should be fixed by PR #37 (along with previous PRs #22, #27 and #28).
