### ISSUE TITLE
Assertions failing with error "TypeError: string indices must be integers, not str"

### ISSUE THREAD

**Issue by rajbg2000** [DMTF/Redfish-Service-Conformance-Check#38]
GET request receiving JSON data as string and tool fails to parse this data. 

Traceback (most recent call last):
  File "rf_client.py", line 780, in <module>
    main()
  File "rf_client.py", line 774, in main
    rfs_test.run(sut)
  File "/usr/bin/rfs_test/__init__.py", line 39, in run
    TEST_protocol_details.run(sut, log)
  File "/usr/bin/rfs_test/TEST_protocol_details.py", line 5091, in run
    assertion_status = Assertion_6_5_8(self, log)
  File "/usr/bin/rfs_test/TEST_protocol_details.py", line 4495, in Assertion_6_5_8
    resource = json_payload['@odata.context']
TypeError: string indices must be integers, not str

**Comment by billdodd** [comment]
I can add some additional checking to be sure the response has been parsed into a JSON object (dict) and thereby avoid the TypeError and early program termination.

The question is why didn't the response get parsed into JSON? From code inspection, the most likely reason would be that the response from the service did not include a Content-Type header with a value that included "application/json".
